// ============================================================
// AUREXIA LEGENDS — 20 CHAMPIONS DATA LIBRARY
// All characters generated by Aurexia AI. No demos, no placeholders.
// ============================================================

export type Rarity = "LEGENDARY" | "EPIC" | "RARE" | "UNCOMMON" | "COMMON"
export type Role = "Warrior" | "Mage" | "Assassin" | "Guardian" | "Support" | "Hunter" | "Tank"
export type Element = "Fire" | "Ice" | "Lightning" | "Shadow" | "Nature" | "Void" | "Holy" | "Steel" | "Water" | "Time" | "Arcane" | "Blood"

export interface Skill {
  name: string
  description: string
  damage: number
  manaCost: number
  cooldown: number // in seconds
  type: "active" | "passive" | "ultimate"
}

export interface Champion {
  id: number
  slug: string
  name: string
  title: string
  lore: string
  image: string
  role: Role
  element: Element
  rarity: Rarity
  price: number // in AXC
  stats: {
    hp: number
    maxHp: number
    mana: number
    maxMana: number
    attack: number
    defense: number
    magic: number
    speed: number
    critRate: number
  }
  skills: [Skill, Skill, Skill, Skill]
  powerScore: number
  winRate: number
  pickRate: number
  owned?: boolean
}

export const CHAMPIONS: Champion[] = [
  {
    id: 1,
    slug: "auron-eternal",
    name: "Auron",
    title: "The Eternal Guardian",
    lore: "Before the first star ignited, Auron stood at the edge of the void and chose to protect. He has watched civilizations rise and crumble into dust. Now he stands at the threshold of the digital age, an immovable force between chaos and order. His armor is forged from crystallized starlight. His oath is unbreakable.",
    image: "/champions/champion-01.jpg",
    role: "Guardian",
    element: "Holy",
    rarity: "LEGENDARY",
    price: 2400,
    stats: { hp: 4200, maxHp: 4200, mana: 800, maxMana: 800, attack: 88, defense: 96, magic: 72, speed: 58, critRate: 12 },
    skills: [
      { name: "Starlight Strike", description: "Channels stellar energy into a devastating blow that ignores 30% of enemy defense.", damage: 340, manaCost: 60, cooldown: 5, type: "active" },
      { name: "Celestial Barrier", description: "Creates an impenetrable shield absorbing 800 damage for 4 seconds.", damage: 0, manaCost: 80, cooldown: 12, type: "active" },
      { name: "Guardian's Wrath", description: "Passive: Increases defense by 15% when HP drops below 40%.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Eternity's Edge", description: "ULTIMATE: Unleashes the raw power of creation. Deals 1200 holy damage to all enemies and stuns them for 2.5 seconds.", damage: 1200, manaCost: 200, cooldown: 90, type: "ultimate" },
    ],
    powerScore: 9847,
    winRate: 58.2,
    pickRate: 14.3,
  },
  {
    id: 2,
    slug: "seraphine-void",
    name: "Seraphine",
    title: "Keeper of the Void",
    lore: "She was a quantum physicist who stared too long into the fabric of space-time. The void stared back and welcomed her. Now she moves between dimensions at will, harvesting the dark energy that powers her spells. Those who face her report seeing their own deaths before the battle begins. She never loses because she has already seen the outcome.",
    image: "/champions/champion-02.jpg",
    role: "Mage",
    element: "Void",
    rarity: "EPIC",
    price: 1800,
    stats: { hp: 2100, maxHp: 2100, mana: 1800, maxMana: 1800, attack: 42, defense: 38, magic: 98, speed: 74, critRate: 28 },
    skills: [
      { name: "Void Bolt", description: "Fires a bolt of void energy that deals 280 magic damage and reduces enemy magic resistance.", damage: 280, manaCost: 50, cooldown: 3, type: "active" },
      { name: "Dimensional Shift", description: "Teleports to target location and deals 200 AoE damage on arrival.", damage: 200, manaCost: 90, cooldown: 15, type: "active" },
      { name: "Dark Resonance", description: "Passive: Every 3rd spell deals 50% bonus damage.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Reality Collapse", description: "ULTIMATE: Tears open the void beneath all enemies. 900 damage per second for 3 seconds. Enemies cannot move.", damage: 2700, manaCost: 220, cooldown: 110, type: "ultimate" },
    ],
    powerScore: 8234,
    winRate: 54.7,
    pickRate: 18.9,
  },
  {
    id: 3,
    slug: "khal-nexus",
    name: "Khal",
    title: "Titan Warlord",
    lore: "Once a general who won a hundred wars, Khal was betrayed and left to die in the heart of a collapsing star. He did not die. He became something more. Now his body is reinforced with the compressed matter of dead suns. Every swing of his blade reshapes the terrain. His war cry alone shatters mountains. He came back. And he is not finished.",
    image: "/champions/champion-03.jpg",
    role: "Warrior",
    element: "Fire",
    rarity: "RARE",
    price: 950,
    stats: { hp: 3600, maxHp: 3600, mana: 600, maxMana: 600, attack: 94, defense: 78, magic: 35, speed: 62, critRate: 22 },
    skills: [
      { name: "Inferno Slash", description: "A blazing sword arc dealing 380 fire damage and applying burn for 3 seconds.", damage: 380, manaCost: 70, cooldown: 6, type: "active" },
      { name: "Solar Stomp", description: "Slams the ground, dealing 250 damage and slowing all nearby enemies by 40%.", damage: 250, manaCost: 65, cooldown: 10, type: "active" },
      { name: "Dead Star Body", description: "Passive: Reduces all incoming physical damage by 18%.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Supernova Rage", description: "ULTIMATE: Transforms into a living star for 6 seconds. Attack speed doubles, deals 600 bonus fire damage on each hit.", damage: 600, manaCost: 180, cooldown: 100, type: "ultimate" },
    ],
    powerScore: 7156,
    winRate: 51.3,
    pickRate: 12.1,
  },
  {
    id: 4,
    slug: "nova-surge",
    name: "Nova",
    title: "Quantum Speedster",
    lore: "Nova does not run. She arrives before she leaves. A quantum anomaly given consciousness, she exists in multiple timelines simultaneously. She has already won every battle she has ever entered — the physical manifestation is merely a formality. Her enemies never see her. They only feel the aftermath of a thousand strikes that happened all at once.",
    image: "/champions/champion-04.jpg",
    role: "Assassin",
    element: "Lightning",
    rarity: "LEGENDARY",
    price: 2100,
    stats: { hp: 2400, maxHp: 2400, mana: 1200, maxMana: 1200, attack: 92, defense: 48, magic: 65, speed: 99, critRate: 42 },
    skills: [
      { name: "Quantum Strike", description: "Strikes three times in a split second, each hit dealing 160 lightning damage.", damage: 480, manaCost: 55, cooldown: 4, type: "active" },
      { name: "Time Fracture", description: "Temporarily freezes time for 1.5 seconds. Only Nova can act.", damage: 0, manaCost: 100, cooldown: 20, type: "active" },
      { name: "Parallel Existence", description: "Passive: 20% chance to dodge any incoming attack completely.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Timeline Collapse", description: "ULTIMATE: Deals damage equal to all attacks that would have been made in 5 seconds, instantly. Average 3200 damage.", damage: 3200, manaCost: 250, cooldown: 120, type: "ultimate" },
    ],
    powerScore: 9123,
    winRate: 57.8,
    pickRate: 21.4,
  },
  {
    id: 5,
    slug: "vex-shadowblade",
    name: "Vex",
    title: "The Shadowblade",
    lore: "Vex was never meant to exist. Born in the space between light and dark, she is the embodiment of a shadow that gained consciousness and decided it wanted more than to follow. She mastered assassination before she learned to speak. By the time she was grown, no contract was too dangerous, no target too powerful. She does not hunt. She simply appears, and it is over.",
    image: "/champions/champion-05.jpg",
    role: "Assassin",
    element: "Shadow",
    rarity: "EPIC",
    price: 1650,
    stats: { hp: 1900, maxHp: 1900, mana: 1000, maxMana: 1000, attack: 98, defense: 35, magic: 58, speed: 92, critRate: 48 },
    skills: [
      { name: "Shadow Stab", description: "Materializes from shadow to strike for 420 damage. Refunds cooldown if it kills the target.", damage: 420, manaCost: 45, cooldown: 6, type: "active" },
      { name: "Void Step", description: "Becomes invisible for 3 seconds and teleports behind target.", damage: 0, manaCost: 70, cooldown: 14, type: "active" },
      { name: "Deathmark", description: "Passive: First hit on an enemy in combat deals 60% bonus damage.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Shadow Execution", description: "ULTIMATE: Deals 400% of attack as shadow damage. Instantly kills targets below 20% HP.", damage: 1600, manaCost: 200, cooldown: 90, type: "ultimate" },
    ],
    powerScore: 8891,
    winRate: 56.1,
    pickRate: 16.7,
  },
  {
    id: 6,
    slug: "sylvan-verdant",
    name: "Sylvan",
    title: "Voice of the Ancient Forest",
    lore: "The oldest trees in the world whisper her name. Sylvan is not a being of the forest — she IS the forest. Ten thousand years of growth, death, and rebirth compressed into a single consciousness. She speaks and roots tear through stone. She breathes and the ground blooms with lethal flora. She has seen empires fall and she will see many more. She does not hurry. She does not need to.",
    image: "/champions/champion-06.jpg",
    role: "Support",
    element: "Nature",
    rarity: "RARE",
    price: 880,
    stats: { hp: 3200, maxHp: 3200, mana: 1400, maxMana: 1400, attack: 58, defense: 72, magic: 85, speed: 55, critRate: 15 },
    skills: [
      { name: "Thorn Whip", description: "Lashes with a vine dealing 220 nature damage and rooting the enemy for 1.5 seconds.", damage: 220, manaCost: 50, cooldown: 5, type: "active" },
      { name: "Lifeblossom", description: "Heals an ally for 650 HP and grants 20% movement speed for 3 seconds.", damage: -650, manaCost: 80, cooldown: 12, type: "active" },
      { name: "Ancient Regrowth", description: "Passive: Regenerates 1.5% of max HP every second in combat.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "World Tree", description: "ULTIMATE: Summons a world tree that heals all allies for 400 HP/sec and deals 300 nature damage to all enemies for 5 seconds.", damage: 1500, manaCost: 200, cooldown: 100, type: "ultimate" },
    ],
    powerScore: 6842,
    winRate: 52.8,
    pickRate: 9.3,
  },
  {
    id: 7,
    slug: "thor-axcite",
    name: "Thor'axc",
    title: "The Thunder Sovereign",
    lore: "Born during the greatest electromagnetic storm in recorded history, Thor'axc carries the living charge of a billion lightning bolts within his mortal frame. His hammer is not a weapon — it is a lightning rod that channels the fury of the atmosphere itself. He does not fight. He conducts. And the music he plays is thunder.",
    image: "/champions/champion-07.jpg",
    role: "Warrior",
    element: "Lightning",
    rarity: "EPIC",
    price: 1400,
    stats: { hp: 3000, maxHp: 3000, mana: 900, maxMana: 900, attack: 86, defense: 68, magic: 76, speed: 70, critRate: 25 },
    skills: [
      { name: "Lightning Hammer", description: "Hurls electrified hammer dealing 340 lightning damage and chaining to 2 nearby enemies for 170 each.", damage: 340, manaCost: 65, cooldown: 6, type: "active" },
      { name: "Thunder Clap", description: "Generates a shockwave dealing 280 damage and stunning all enemies within 6 meters for 1.8 seconds.", damage: 280, manaCost: 80, cooldown: 14, type: "active" },
      { name: "Storm Body", description: "Passive: 25% chance to shock attacker for 80 lightning damage on being hit.", damage: 80, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Thundergod's Wrath", description: "ULTIMATE: Calls down 5 massive lightning strikes on the battlefield. Each deals 600 damage. Total 3000 damage.", damage: 3000, manaCost: 230, cooldown: 115, type: "ultimate" },
    ],
    powerScore: 7890,
    winRate: 53.4,
    pickRate: 13.8,
  },
  {
    id: 8,
    slug: "malachar-void",
    name: "Malachar",
    title: "The Void Sovereign",
    lore: "Malachar is what remains when a universe ends. He is entropy given form, the inevitable heat death of all things walking in the present tense. He does not seek destruction — destruction simply follows him the way a shadow follows light. Scientists who study the void report his presence through quantum anomalies that defy all known physics. Facing him is not battle. It is the experience of inevitability.",
    image: "/champions/champion-08.jpg",
    role: "Mage",
    element: "Void",
    rarity: "LEGENDARY",
    price: 2800,
    stats: { hp: 2600, maxHp: 2600, mana: 2000, maxMana: 2000, attack: 55, defense: 60, magic: 99, speed: 68, critRate: 35 },
    skills: [
      { name: "Entropic Ray", description: "Fires a beam of pure entropy dealing 460 void damage and reducing target's max HP by 5%.", damage: 460, manaCost: 75, cooldown: 5, type: "active" },
      { name: "Gravity Well", description: "Creates a gravitational anomaly pulling all enemies to center and dealing 350 damage.", damage: 350, manaCost: 90, cooldown: 16, type: "active" },
      { name: "Void Presence", description: "Passive: Reduces all nearby enemy magic resistance by 20%.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Universal Collapse", description: "ULTIMATE: Collapses reality on all enemies. 800 void damage instantly, then 400 damage over 4 seconds. Ignores all resistances.", damage: 2400, manaCost: 280, cooldown: 130, type: "ultimate" },
    ],
    powerScore: 9654,
    winRate: 59.1,
    pickRate: 11.2,
  },
  {
    id: 9,
    slug: "celestia-radiance",
    name: "Celestia",
    title: "The Radiant Angel",
    lore: "Heaven's greatest warrior volunteered to descend. Celestia did not fall — she dove, wings spread, golden sword gleaming, with a war cry that echoed through seven heavens. She fights not because she is commanded to but because she chose to stand between the innocent and those who would harm them. Her light does not merely illuminate — it purifies. Her presence alone makes evil retreat.",
    image: "/champions/champion-09.jpg",
    role: "Support",
    element: "Holy",
    rarity: "LEGENDARY",
    price: 2600,
    stats: { hp: 2800, maxHp: 2800, mana: 1600, maxMana: 1600, attack: 72, defense: 82, magic: 94, speed: 76, critRate: 20 },
    skills: [
      { name: "Holy Smite", description: "A radiant strike dealing 300 holy damage. Undead and void enemies take 100% bonus damage.", damage: 300, manaCost: 55, cooldown: 4, type: "active" },
      { name: "Divine Shield", description: "Grants target ally immunity to all damage for 2.5 seconds and heals 400 HP.", damage: -400, manaCost: 100, cooldown: 18, type: "active" },
      { name: "Celestial Aura", description: "Passive: Heals all allies for 25 HP every second. Reduces cooldowns by 10%.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Heaven's Judgment", description: "ULTIMATE: Calls divine judgment on all enemies. 700 holy damage and blinds all enemies for 3 seconds. Heals all allies for 500 HP.", damage: 700, manaCost: 250, cooldown: 120, type: "ultimate" },
    ],
    powerScore: 9340,
    winRate: 57.6,
    pickRate: 15.4,
  },
  {
    id: 10,
    slug: "korrax-infernal",
    name: "Korrax",
    title: "Warlord of Infernal Depths",
    lore: "Korrax was once the greatest warrior who ever lived. He refused death itself, making a pact with forces darker than any mortal should dare contact. Now he straddles both worlds — too powerful for hell to contain and too corrupted for the living realm to accept. His chains bind the souls of those he has defeated. His armor is forged from the compressed regrets of the damned. He is magnificently, terrifyingly unstoppable.",
    image: "/champions/champion-10.jpg",
    role: "Tank",
    element: "Fire",
    rarity: "LEGENDARY",
    price: 3200,
    stats: { hp: 5800, maxHp: 5800, mana: 600, maxMana: 600, attack: 90, defense: 99, magic: 60, speed: 45, critRate: 18 },
    skills: [
      { name: "Hellfire Slam", description: "Crashes down with infernal force dealing 400 fire damage in a large area.", damage: 400, manaCost: 70, cooldown: 6, type: "active" },
      { name: "Soul Chain", description: "Chains an enemy, dealing 200 damage and reducing their attack by 35% for 5 seconds.", damage: 200, manaCost: 80, cooldown: 12, type: "active" },
      { name: "Infernal Skin", description: "Passive: Reduces all incoming damage by 22%. Attackers receive 50 fire damage.", damage: 50, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Apocalypse Rising", description: "ULTIMATE: Opens a hellgate under all enemies. 500 damage per second for 4 seconds. Cannot be interrupted.", damage: 2000, manaCost: 200, cooldown: 120, type: "ultimate" },
    ],
    powerScore: 9512,
    winRate: 56.9,
    pickRate: 10.8,
  },
  {
    id: 11,
    slug: "nexion-cyber",
    name: "Nexion",
    title: "The Cyber Samurai",
    lore: "He deleted his organic memories and uploaded pure combat algorithms. Nexion is the convergence of ancient bushido and machine perfection. His neural interface processes 10,000 scenarios per millisecond, selecting the optimal kill sequence before his blade has left its sheath. He has never lost a duel. He cannot feel fear because he erased the subroutine.",
    image: "/champions/champion-11.jpg",
    role: "Assassin",
    element: "Steel",
    rarity: "EPIC",
    price: 1750,
    stats: { hp: 2200, maxHp: 2200, mana: 800, maxMana: 800, attack: 96, defense: 55, magic: 50, speed: 88, critRate: 38 },
    skills: [
      { name: "Neon Katana", description: "A perfectly calculated strike dealing 360 damage. Ignores 25% of armor.", damage: 360, manaCost: 50, cooldown: 4, type: "active" },
      { name: "Combat Protocol", description: "Analyzes enemy pattern, dodging all attacks for 2 seconds and counterattacking for 300 damage.", damage: 300, manaCost: 85, cooldown: 16, type: "active" },
      { name: "Algorithmic Precision", description: "Passive: Every 4th attack is a guaranteed critical hit dealing 220% damage.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Zero Point Execution", description: "ULTIMATE: Calculates and executes 8 perfect strikes simultaneously. Total 2800 damage. Each hit is a guaranteed critical.", damage: 2800, manaCost: 200, cooldown: 100, type: "ultimate" },
    ],
    powerScore: 8567,
    winRate: 55.3,
    pickRate: 17.2,
  },
  {
    id: 12,
    slug: "raven-bloodmoon",
    name: "Raven",
    title: "Blood Moon Huntress",
    lore: "Under the blood moon, she made a pact that cost her everything and gave her everything. Raven hunts the most dangerous quarry: those who believe themselves beyond reach. No fortress has kept her out. No bodyguard has kept her target alive. She is not driven by cruelty — she is driven by a code so absolute it borders on religion. The moon rises. The contract is fulfilled. Always.",
    image: "/champions/champion-12.jpg",
    role: "Hunter",
    element: "Blood",
    rarity: "EPIC",
    price: 1550,
    stats: { hp: 2300, maxHp: 2300, mana: 900, maxMana: 900, attack: 90, defense: 52, magic: 68, speed: 85, critRate: 40 },
    skills: [
      { name: "Blood Arrow", description: "Fires a blood-tipped arrow dealing 280 damage and applying bleed for 4 seconds (80 damage/sec).", damage: 280, manaCost: 45, cooldown: 4, type: "active" },
      { name: "Wolf Pack", description: "Summons 2 shadow wolves that each deal 150 damage per attack for 6 seconds.", damage: 900, manaCost: 90, cooldown: 18, type: "active" },
      { name: "Blood Scent", description: "Passive: Gains 15% attack speed for each bleeding enemy. Stacks up to 3 times.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Moon's Curse", description: "ULTIMATE: Marks all enemies with the blood moon curse. Enemies take 350% more bleed damage for 8 seconds. Applies bleed to all.", damage: 2400, manaCost: 210, cooldown: 105, type: "ultimate" },
    ],
    powerScore: 8123,
    winRate: 54.2,
    pickRate: 14.9,
  },
  {
    id: 13,
    slug: "garath-crystal",
    name: "Garath",
    title: "The Crystal Colossus",
    lore: "The earth had a secret buried for ten million years: a consciousness crystallizing in the mantle, learning patience as magma cooled around it. Garath emerged not from a womb but from a mountain, shattering it in his awakening. He does not walk with haste. Every step reshapes the terrain. His body is a geological event. His fist is a tectonic shift. He has all the time in the world.",
    image: "/champions/champion-13.jpg",
    role: "Tank",
    element: "Steel",
    rarity: "RARE",
    price: 1100,
    stats: { hp: 6200, maxHp: 6200, mana: 400, maxMana: 400, attack: 80, defense: 99, magic: 30, speed: 38, critRate: 10 },
    skills: [
      { name: "Crystal Fist", description: "A colossal punch dealing 450 damage and fracturing target's defense by 20% for 8 seconds.", damage: 450, manaCost: 60, cooldown: 6, type: "active" },
      { name: "Geo Barrier", description: "Raises a crystal wall absorbing 1200 incoming damage for 6 seconds.", damage: 0, manaCost: 70, cooldown: 20, type: "active" },
      { name: "Mountain Skin", description: "Passive: The first attack each second deals 80 damage back to the attacker.", damage: 80, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Continental Shift", description: "ULTIMATE: Shatters the ground, dealing 600 damage to all enemies and creating impassable terrain for 4 seconds.", damage: 600, manaCost: 150, cooldown: 90, type: "ultimate" },
    ],
    powerScore: 7234,
    winRate: 52.1,
    pickRate: 8.7,
  },
  {
    id: 14,
    slug: "yuki-ninetails",
    name: "Yuki",
    title: "The Nine-Tailed Spirit",
    lore: "She has lived nine lifetimes. Each time she died, she was reborn with the memories of every life before. Yuki has loved empires and watched them fall. She has mastered every school of magic across nine centuries. Her ninth life is her last, and she intends to make it count. Her golden flames do not burn — they purify. Those she deems worthy are blessed. Those she deems corrupt simply cease to exist.",
    image: "/champions/champion-14.jpg",
    role: "Mage",
    element: "Holy",
    rarity: "LEGENDARY",
    price: 2900,
    stats: { hp: 2400, maxHp: 2400, mana: 1900, maxMana: 1900, attack: 65, defense: 55, magic: 97, speed: 80, critRate: 30 },
    skills: [
      { name: "Spirit Flame", description: "Launches sacred fox fire dealing 320 magic damage and removing 1 buff from the enemy.", damage: 320, manaCost: 55, cooldown: 4, type: "active" },
      { name: "Nine Lives", description: "Gains a stack of life insurance. On death, revives with 30% HP (once per stack, max 9 stacks over a lifetime).", damage: 0, manaCost: 0, cooldown: 30, type: "active" },
      { name: "Ancestral Wisdom", description: "Passive: Reduces mana cost of all spells by 15% and increases magic damage by 12%.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Spirit World Gate", description: "ULTIMATE: Opens the spirit realm for 5 seconds. All allies become invincible. All enemies take 350 magic damage per second.", damage: 1750, manaCost: 300, cooldown: 140, type: "ultimate" },
    ],
    powerScore: 9289,
    winRate: 58.8,
    pickRate: 13.1,
  },
  {
    id: 15,
    slug: "morvex-plague",
    name: "Morvex",
    title: "Doctor of the Last Plague",
    lore: "He studied death so thoroughly that he achieved a kind of symbiosis with it. Morvex carries within his body 847 catalogued toxins and the cure to none of them, because cures are not his purpose. His plague is not random — it is precise. He can select exactly which systems to fail, how quickly, and in what sequence. He considers it artistry. His patients might disagree, if they could still speak.",
    image: "/champions/champion-15.jpg",
    role: "Mage",
    element: "Shadow",
    rarity: "EPIC",
    price: 1600,
    stats: { hp: 2000, maxHp: 2000, mana: 1700, maxMana: 1700, attack: 48, defense: 42, magic: 94, speed: 65, critRate: 26 },
    skills: [
      { name: "Toxic Vial", description: "Hurls a vial of plague dealing 180 damage and poisoning for 6 seconds (65 damage/sec).", damage: 180, manaCost: 50, cooldown: 5, type: "active" },
      { name: "Plague Cloud", description: "Creates a toxic cloud dealing 200 damage/sec for 3 seconds in an area.", damage: 600, manaCost: 85, cooldown: 14, type: "active" },
      { name: "Contagion", description: "Passive: Poison effects spread to adjacent enemies when a poisoned enemy dies.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Pandemic Protocol", description: "ULTIMATE: Infects all enemies with an incurable super-plague. 200 damage per second for 10 seconds. Spreads to nearby enemies if not all affected.", damage: 2000, manaCost: 240, cooldown: 120, type: "ultimate" },
    ],
    powerScore: 7987,
    winRate: 53.9,
    pickRate: 11.6,
  },
  {
    id: 16,
    slug: "tidal-krynn",
    name: "Krynn",
    title: "Warden of the Deep",
    lore: "The ocean kept a secret for a billion years. Krynn is that secret. Born in the deepest trench where pressure creates new forms of matter, he carries the weight of ten miles of ocean in his soul. Sailors from three continents have sworn they saw his silhouette beneath the waves before storms that sank entire fleets. He does not hate humanity. He is simply indifferent in the way only the ocean can be.",
    image: "/champions/champion-16.jpg",
    role: "Tank",
    element: "Water",
    rarity: "RARE",
    price: 1050,
    stats: { hp: 4800, maxHp: 4800, mana: 1100, maxMana: 1100, attack: 76, defense: 88, magic: 72, speed: 52, critRate: 14 },
    skills: [
      { name: "Trident Strike", description: "A powerful thrust dealing 310 damage and pushing the enemy back 5 meters.", damage: 310, manaCost: 65, cooldown: 5, type: "active" },
      { name: "Tidal Surge", description: "Summons a massive wave dealing 260 damage to all enemies and slowing them by 50% for 3 seconds.", damage: 260, manaCost: 80, cooldown: 14, type: "active" },
      { name: "Oceanic Resilience", description: "Passive: Regenerates 2% max HP every 3 seconds while in combat.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Whirlpool Abyss", description: "ULTIMATE: Creates a massive whirlpool pulling all enemies to center, dealing 1800 damage and drowning them for 2 seconds.", damage: 1800, manaCost: 200, cooldown: 110, type: "ultimate" },
    ],
    powerScore: 7445,
    winRate: 52.6,
    pickRate: 9.8,
  },
  {
    id: 17,
    slug: "chronus-timeweaver",
    name: "Chronus",
    title: "Architect of Time",
    lore: "He did not discover how to manipulate time. Time consulted him. Chronus is older than his own birth — a temporal paradox in the shape of a man, carrying the memory of every moment across every timeline. He speaks rarely because he knows how every conversation ends. He acts with absolute precision because he has already watched himself succeed. To face him is to fight inevitability itself.",
    image: "/champions/champion-17.jpg",
    role: "Mage",
    element: "Time",
    rarity: "LEGENDARY",
    price: 3100,
    stats: { hp: 2200, maxHp: 2200, mana: 2100, maxMana: 2100, attack: 60, defense: 58, magic: 99, speed: 72, critRate: 33 },
    skills: [
      { name: "Timestop Bolt", description: "Fires a bolt that freezes the target in time for 2 seconds and deals 350 damage.", damage: 350, manaCost: 70, cooldown: 8, type: "active" },
      { name: "Rewind", description: "Rewinds ally to their state 3 seconds ago, restoring their HP and removing debuffs.", damage: 0, manaCost: 110, cooldown: 20, type: "active" },
      { name: "Temporal Mastery", description: "Passive: Cooldowns are reduced by 20%. Can see 1 second into the future (dodge rating +15%).", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Age of Oblivion", description: "ULTIMATE: Ages all enemies to dust. Deals damage equal to 40% of their remaining HP and reduces their stats by 30% for 8 seconds.", damage: 0, manaCost: 300, cooldown: 150, type: "ultimate" },
    ],
    powerScore: 9601,
    winRate: 60.2,
    pickRate: 8.4,
  },
  {
    id: 18,
    slug: "iron-magnus",
    name: "Magnus",
    title: "Grand Commander of the Iron Legion",
    lore: "A hundred battlefields. A hundred victories. Magnus does not understand defeat any more than he understands fear — not because he lacks imagination, but because neither has ever been his experience. His Iron Legion has never broken. His strategy has never failed. He sees the battlefield as a puzzle already solved, and his role is simply to execute the solution. He is not a warrior. He is a certainty.",
    image: "/champions/champion-18.jpg",
    role: "Warrior",
    element: "Steel",
    rarity: "RARE",
    price: 1200,
    stats: { hp: 3400, maxHp: 3400, mana: 700, maxMana: 700, attack: 88, defense: 85, magic: 45, speed: 65, critRate: 22 },
    skills: [
      { name: "Iron Judgment", description: "A calculated strike dealing 380 physical damage and reducing enemy attack by 25% for 5 seconds.", damage: 380, manaCost: 65, cooldown: 5, type: "active" },
      { name: "Rally the Legion", description: "Buffs all allies for 20% attack and 15% defense for 8 seconds.", damage: 0, manaCost: 90, cooldown: 20, type: "active" },
      { name: "Veteran's Resolve", description: "Passive: Gains 5% additional stats for each enemy defeated in combat.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Iron Conquest", description: "ULTIMATE: Charges through all enemies dealing 500 damage and stunning them. Then all allies gain +40% attack for 10 seconds.", damage: 500, manaCost: 180, cooldown: 100, type: "ultimate" },
    ],
    powerScore: 7678,
    winRate: 53.7,
    pickRate: 12.4,
  },
  {
    id: 19,
    slug: "pyra-phoenix",
    name: "Pyra",
    title: "The Undying Phoenix",
    lore: "She has died 144 times. She has counted. Each death is a rebirth into something fiercer, something more refined, something that has learned from every wound ever inflicted. Pyra does not avoid pain — she metabolizes it into power. Her feathers carry the heat of every fire she has ever survived. Her battle cry is the sound of a thousand rebirths compressed into a single moment of defiant existence.",
    image: "/champions/champion-19.jpg",
    role: "Warrior",
    element: "Fire",
    rarity: "EPIC",
    price: 1900,
    stats: { hp: 2800, maxHp: 2800, mana: 1000, maxMana: 1000, attack: 92, defense: 62, magic: 78, speed: 82, critRate: 30 },
    skills: [
      { name: "Phoenix Talon", description: "Rakes with burning talons dealing 360 fire damage and applying a burn for 3 seconds.", damage: 360, manaCost: 60, cooldown: 4, type: "active" },
      { name: "Ascent", description: "Launches into the air and crashes down dealing 420 damage in a large area.", damage: 420, manaCost: 85, cooldown: 14, type: "active" },
      { name: "Rebirth Ember", description: "Passive: On death, revives once per battle with 50% HP and all cooldowns reset.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Eternal Pyre", description: "ULTIMATE: Transforms the battlefield into an inferno for 6 seconds. All enemies take 400 fire damage per second. Cannot be extinguished.", damage: 2400, manaCost: 220, cooldown: 125, type: "ultimate" },
    ],
    powerScore: 8934,
    winRate: 56.4,
    pickRate: 15.8,
  },
  {
    id: 20,
    slug: "axiom-inventor",
    name: "Axiom",
    title: "The Arcane Architect",
    lore: "He built the device that splits atoms with his bare hands on a Tuesday afternoon. The device to fold space came to him in the shower. Axiom is the most dangerous mind in any universe he has visited, and he has visited several. He does not fight with strength — he fights with impossibility. By the time his enemy understands what weapon just struck them, he has already built something more terrifying.",
    image: "/champions/champion-20.jpg",
    role: "Support",
    element: "Arcane",
    rarity: "EPIC",
    price: 1700,
    stats: { hp: 2100, maxHp: 2100, mana: 1600, maxMana: 1600, attack: 55, defense: 50, magic: 92, speed: 68, critRate: 28 },
    skills: [
      { name: "Hextech Blast", description: "Fires an overcharged energy bolt dealing 300 arcane damage and applying a 2-second electro-stun.", damage: 300, manaCost: 60, cooldown: 5, type: "active" },
      { name: "Deploy Turret", description: "Places an automated turret that deals 120 damage per second for 8 seconds.", damage: 960, manaCost: 90, cooldown: 18, type: "active" },
      { name: "Adaptive Systems", description: "Passive: After being damaged, gains 10% resistance to that damage type for 10 seconds.", damage: 0, manaCost: 0, cooldown: 0, type: "passive" },
      { name: "Arcane Supercollider", description: "ULTIMATE: Fires a particle accelerator beam across the entire arena. Deals 2600 arcane damage to all enemies hit. Width increases with each enemy pierced.", damage: 2600, manaCost: 260, cooldown: 130, type: "ultimate" },
    ],
    powerScore: 8456,
    winRate: 54.9,
    pickRate: 13.7,
  },
]

export const getRarityColor = (rarity: Rarity): string => {
  switch (rarity) {
    case "LEGENDARY": return "text-yellow-400"
    case "EPIC": return "text-purple-400"
    case "RARE": return "text-blue-400"
    case "UNCOMMON": return "text-green-400"
    default: return "text-gray-400"
  }
}

export const getRarityBorder = (rarity: Rarity): string => {
  switch (rarity) {
    case "LEGENDARY": return "border-yellow-400/60 shadow-[0_0_20px_rgba(250,204,21,0.3)]"
    case "EPIC": return "border-purple-400/60 shadow-[0_0_20px_rgba(192,132,252,0.3)]"
    case "RARE": return "border-blue-400/60 shadow-[0_0_20px_rgba(96,165,250,0.3)]"
    case "UNCOMMON": return "border-green-400/40"
    default: return "border-white/20"
  }
}

export const getRarityBg = (rarity: Rarity): string => {
  switch (rarity) {
    case "LEGENDARY": return "bg-yellow-400/10"
    case "EPIC": return "bg-purple-400/10"
    case "RARE": return "bg-blue-400/10"
    case "UNCOMMON": return "bg-green-400/10"
    default: return "bg-white/5"
  }
}

export const getElementColor = (element: Element): string => {
  switch (element) {
    case "Fire": return "text-orange-400"
    case "Ice": return "text-cyan-300"
    case "Lightning": return "text-yellow-300"
    case "Shadow": return "text-purple-300"
    case "Nature": return "text-green-400"
    case "Void": return "text-violet-400"
    case "Holy": return "text-amber-300"
    case "Steel": return "text-slate-300"
    case "Water": return "text-blue-300"
    case "Time": return "text-teal-300"
    case "Arcane": return "text-fuchsia-400"
    case "Blood": return "text-red-400"
    default: return "text-gray-300"
  }
}

export const ELEMENT_ICONS: Record<Element, string> = {
  Fire: "🔥", Ice: "❄", Lightning: "⚡", Shadow: "🌑",
  Nature: "🌿", Void: "🌀", Holy: "✦", Steel: "⚙",
  Water: "💧", Time: "⌛", Arcane: "✦", Blood: "◈"
}
